name: YourLegacy
favicon: null
layout_spectrum: 0.3291318181436509
typography_spectrum: 0.18000308517366648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.35849661799147725
  lightness: 0.6240404858253896
  saturation: 0.5163259021937847
  rhythmicContrast: 0.2706477416213602
purpose: []
